import type { Metadata } from 'next';
import './globals.css';
import '@/styles/theme.css';
import RootStyleRegistry from '@/app/emotion';
import ClientQueryProvider from '@/config/ClientQueryProvider';
import localFont from 'next/font/local';

const pretendard = localFont({
  src: '../app/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body>
        <ClientQueryProvider>
          <RootStyleRegistry>
            <main>{children}</main>
          </RootStyleRegistry>
        </ClientQueryProvider>
      </body>
    </html>
  );
}
